name: Add coding line to Python files

on:
  push:
    branches:
      - master

jobs:
  add_coding_line:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Add coding line to Python files
        run: |
          find . -type f -name "*.py" -not -path "./.deprecated/*" \
          | while read file; do
            if ! head -n 1 "$file" | grep -q 'coding: utf-8'; then
              sed -i '1i # -*- coding: utf-8 -*-' "$file"
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if any changes were made
          if [[ -n $(git status -s) ]]; then
            git commit -am "Добавление строки с кодировкой"
            git push
          else
            echo "No changes were made to the files."
          fi
