name: Trim whitespace and add newline

on:
  push

jobs:
  trim-and-newline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trim whitespace and add newline
        run: |
          find . -type f -not -path './.git*/*' -exec grep -Iq . {} \; -exec sed -i -e 's/[[:space:]]*$//' -e '$a\' {} +
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if any changes were made
          if [[ -n $(git status -s) ]]; then
            git commit -am "Добавление строки с кодировкой"
            git push
          else
            echo "No changes were made to the files."
          fi
